### PR TITLE
CPG files and Scanner Interface #7

### PR DESCRIPTION
**Pull request by TuSKan**
- .cpg files added for different encoding
- Scanner interface added to read huge files

### CODE REVIEW

**Comment by twpayne** [comment]
Thank you, this looks excellent.

Please you could rebase this PR on the latest `master` branch to pick up the changes from #9, which should allow the checks to complete.

**Comment by twpayne** [comment]
Thank you again for this. Lint reports a number of problems. Would you be willing to fix them? No worries if you don't have the time -- I would be happy to accept this PR as-is and fix things in a follow-up PR.

**Comment by TuSKan** [comment]
> Thank you again for this. Lint reports a number of problems. Would you be willing to fix them? No worries if you don't have the time -- I would be happy to accept this PR as-is and fix things in a follow-up PR.

I will fix and pass those checks.

**Comment by twpayne** [comment]
Thanks for fixing the lint checks!

The most recent checks are failing because go-shapefile's CI checks that the code runs with the previous stable version of Go (1.20), whereas the new code requires Go 1.21.

Please add a commit that removes [this line](https://github.com/twpayne/go-shapefile/blob/d42f4cc0b961db0b55afdda04970ffd511aa09d3/.github/workflows/main.yml#L27), which will remove the test on Go 1.20.

**Comment by twpayne** [comment]
Ah, and `go.mod` will need a `go 1.21` directive because of the use of `max`.

**Comment by TuSKan** [comment]
I just make some clean version with go 1.19.  Now I think I'll work fine

**Comment by twpayne** [comment]
Thank you very much for this!

**Pull request merged**
